namespace KOG.ECommerce.Models.Enums
{
    public enum Feature
    {
        GetModulesbyRoleID=0,
        // Brand Features
        CreateBrand = 1,
        DeleteBrand,
        EditBrand,
        GetBrandByName,
        GetBrandlist,
        ActiveBrand,
        DeactiveBrand,
        BulkDeleteBrand,
        BulkActivateBrand,
        BulkDeActivateBrand,
        GetBrandsNames,
        GetProductsByBrandId,
        GetBrandByID,
        GetAllBrand,
        SelectBrandList,

        // Classification Features
        CreateClassification = 1000,
        DeleteClassification,
        EditClassification,
        SelectListClassification,
        GetAllClassifications,
        GetClassificationByID,
        // Category Features
        CreateCategory = 2000,
        DeleteCategory,
        EditCategory,
        FilterCategory,
        GetCategorylist,
        ActiveCategory,
        DeactiveCategory,
        BulkDeleteCategory,
        BulkActivateCategory,
        BulkDeActivateCategory,
        SelectCategoryList,
        SelectSubcategoryList,
        GetCategoryIndex,
        GetCategoryById,
        GetSubcategories,
        GetCategoriesNames,
        GetCategoryChildren,

        // City Features
        CreateCity = 3000,
        DeleteCity,
        EditCity,
        GetCityList,
        FilterCity,
        ActiveCity,
        DeactiveCity,
        AddRangeCities,
        BulkDeleteCity,
        BulkDeactivateCity,
        BulkActivateCity,
        GetCitiesbyGovernorateID,
        GetCitybyID,
        SelectCityList,

        // Governorate Features
        CreateGovernorate = 4000,
        DeleteGovernorate,
        EditGovernorate,
        GetGovernorateList,
        GetGovernorateByName,
        ActiveGovernorate,
        DeactiveGovernorate,
        AddRangeGovernrates,
        BulkDeleteGovernorate,
        BulkActivateGovernorate,
        BulkDeactivateGovernorate,
        GetAllGovernorateWithAllCities,
        GetGovernorateDropdownList,
        GetGovernoratebyID,
        InitiatGovernratesAndCities,

        // Product Features
        CreateProduct = 5000,
        DeleteProduct,
        EditProduct,
        GetProductById,
        ActivateProduct,
        DeactivateProduct,
        FilterProductAdminPage,
        GetProductList,
        FilterProducts,
        AddProductToCart,
        RestockProduct,
        RemoveProductFromCart,
        GetAllProductAtCart,
        GetAllProductAtCartWithPrice,
        AddProductToWishlist,
        GetAllProductFromWishlist,
        DeleteProductFromWishlist,
        GetFavoriteProduct,
        GetBestSellerProducts,
        GetNewProducts,
        GetProductsByType,
        GetProductsByCategoryId,
        GetProductsByCommonTags,
        SelectProductList,
        GetProductNameAndPrice,
        ExportProductsToExcel,
        BulkDeleteProduct,
        ActivateProductPoint,
        DeactivateProductPoint,
        BulkActivateProduct,
        BulkDeactivateProduct,
        SearchProductBrandCategoryNames,
        ProductsReport,
        ExportProductsReport,
        // Role Features
        CreateRole = 6000,
        DeleteRole,
        EditRole,
        GetRoleList,
        ActivateRole,
        DeactivateRole,
        AssignFeaturesToRole, 
        AssignBulkFeaturesToRole,
        AssignFeaturesToModule,
        AssignModulesToRole,
        UnassignFeaturesfromRole,
        UnassignFeaturesfromModule,
        UnassignBulkFeaturesToRole,
        SearchRoleByName,

        // Client Features
        ClientRegister = 7000,
        CreateClient,
        EditClient,
        DeleteClient,
        GetClientList,
        SearchClient,
        ActivateClients,
        BulkDeActivateUser,
        DeactivateClients,
        BulkActivateClients,
        BulkDeactivateClients,
        GetClientById,
        GetClientByMobile,
        ApproveTempClient,
        AddTempClient,
        RejectTempClient,
        ApproveUser,
        GetClientViewById,
        //ResetPasswordOTP,
        //ResetPassword,
        ChangePassword,
        //Login,
        //OTPLogin,
        //VerifyOTP,
        //ResendOTP,
        RecoverAccount,
        GetIDOfDefualtShippingAddress,
        ExportClientsToExcel,
        UserData,
        BulkActivateUser,
        SendEmailToClients,
        GetClientsWithDefualtShippingAddress,
        GetAllPendingClient,
        GetAllNotPendingClient,
        GetTempClientByID,
        RejectUser,
        GetAllApproveOrRejectUser,
        GetUserById,
        GetClientDetails,
        ClientReport,
        ExportClientReportToExcel,
        AddClientImage,
        // Client Group Features
        CreateClientGroups = 8000,
        EditClientGroup,
        EditClientGroupTaxExempted,
        DeleteClientGroup,
        ClientGroupsFilterByName,
        GetClientGroupsByID,
        GetClientsByGroupID,
        SelectClientGroupList,
        BulkDeleteClientGroups,

        // Order Features
        PlacedAnOrder = 9000,
        PlacedAnOrderByClient,
        PlacedAnOrderByAdmin,
        GetOrderByNumber,
        GetOrderByID,
        ApproveOrder,
        CancelOrder,
        GetAllOrders,
        GetAllOrdersByUserId,
        OrdersHistory,
        GetOrderStatus,
        GetOrdersStatusPercentage,
        ExportOrdersToExcel,
        Reorder,
        InProcessOrder,
        CompletedOrder,
        EditOrder,
        GetOrderDetails,
        SiteStatistics,
        DeliveredOrder,
        OrdersReports,
        ExportOrdersReportToExcel,
        // Shipping Address Features
        CreateShippingAddress = 10000,
        EditShippingAddress,
        DeleteShippingAddress,
        GetAllShippingAddresses,
        GetShippingAddressesForClient,
        GetShippingAddresseId,
        SetDefaultShippingAddress,
        ApproveShippingAddress,
        RejectShippingAddress,
        AddTempShippingAddress,
        ApproveTempShippingAddresses,
        RejectTempShippingAddress,
        GetAllPendingShippingAddress,
        GetAllNotPendingShippingAddress,
        GetTempShippingAddressByID,

        // Discount Features
        AddDiscount = 11000,
        EditDiscount,
        ActiveDiscount,
        DeactiveDiscount,
        GetAllDiscounts,
        GetDiscountByID,
        BulkActivateDiscount,
        BulkDeactivateDiscount,
        BulkDeleteDiscounts,
        deleteDiscount,

        // Coupon Features
        AddCoupon = 12000,
        EditCoupon,
        ActiveCoupon,
        DeactiveCoupon,

        // Advertisement Features
        CreateAdvertisement = 13000,
        EditAdvertisement,
        DeleteAdvertisement,
        GetAdvertisementByID,
        ActiveAdvertisement,
        GetAllAdvertisement,
        BulkActivateAdvertisement,
        BulkDeactivateAdvertisement,
        BulkDeleteAdvertisement,
        DeactivateAdvertisement,

        // Media Features
        //UploadMedia ,
        DeleteMedia = 14000,
        DeleteBulkMediaBySourceId,
        //SaveMedia,

        // Company Features
        CreateCompany = 15000,
        DeleteCompany,
        EditCompany,
        GetCompanyById,
        ActivateCompany,
        DeactivateCompany,
        FilterCompany,
        FilterByNameCompany,
        GetListCompany,
        SendEmailToCompanies,
        EditPointToCash,
        GetAllApproveOrRejectCompany, 
        GetCompanyRequestById,
        GetAllPendingOrVerifiedCompany,
        CompanyRegister,
        SelectListCompany,
        GetCompaniesNames,
        ExportCompanyToExcel,
        ExportCompanyReportsToExcel,
        CompanyReports,

        // Company Group Features
        CreateCompanyGroup = 16000,
        EditCompanyGroup,
        DeleteCompanyGroup,
        CompanyGroupFilterByName,
        GetCompanyGroupByID,
        GetCompaniesByGroupID,

        // General Featueres
        GetFeaturesbyRoleID = 17000,
        GetFeaturesbyModuleID,
        GetFeatueresListed,
        //AssignAllFeaturesToRole,
        GetVerifyStatusList,
        GetAllVerifiedStatus,
        CreatePage,
        CreateModule,
        CreateUser,
        EditUser,
        FilterUsers,
        ChangeUserPassword,
        ActivateUser,
        DeactivateUser,
        //CheckOTPValidation
        //Notification
        GetAllNotificationMessages = 18000,
        GetAllNotificationMessagesForClient,
        SendNotification,

    }
}
